version: '3.5'

services:

  reverseproxy:
    container_name: solution_proxy
    build:
      context: ./data/nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/nginx/certs:/etc/nginx/certs
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - solution-network
    
  api:
    container_name: solution_api
    image: enterprisesolutionapi:dev
    build:
      context: .
      dockerfile: Enterprise.Solution.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SolutionApi_SolutionSettings__Cache__Host=redisCache
      - SolutionApi_SolutionSettings__Database__Host=postgres
      - SolutionApi_SolutionSettings__MailSettings__Host=mailhog
      
      - SolutionApi_SolutionSettings__Authentication__Schemes__Keycloak__Authority=http://host.docker.internal:8080/auth/realms/enterprise-solution-realm
      - SolutionApi_SolutionSettings__Authentication__Schemes__Keycloak__Metadata=http://host.docker.internal:8080/auth/realms/enterprise-solution-realm/.well-known/openid-configuration
      - SolutionApi_SolutionSettings__Authentication__Schemes__Keycloak__TokenExchange=http://host.docker.internal:8080/auth/realms/enterprise-solution-realm/protocol/openid-connect/token
      - SolutionApi_SolutionSettings__Authentication__Schemes__Keycloak__Users=http://host.docker.internal:8080/auth/admin/realms/enterprise-solution-realm/users
    expose:
      - "5000"
    restart: always
    depends_on:
      - "reverseproxy"
      - "postgres"
      - "redisCache"
      - "keycloak"
    networks:
      - solution-network

  mailhog:
    image: mailhog/mailhog
    container_name: solution_mailhog
    restart: "always"
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      - solution-network
      
  keycloak:
    container_name: solution_keycloak
    image: quay.io/keycloak/keycloak
    depends_on:
      - "postgres"
    command: 
      - start-dev --http-relative-path=/auth
      - --import-realm
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DB: postgres
      KEYCLOAK_DATABASE_HOST: solution_postgres
      KEYCLOAK_DATABASE_NAME: ${POSTGRESQL_DB:-keycloak}
      KEYCLOAK_DATABASE_USERNAME: ${POSTGRESQL_USER:-postgres}
      KEYCLOAK_DATABASE_PASSWORD: ${POSTGRESQL_PASSWORD:-password}
      KEYCLOAK_DATABASE_PORT: "${POSTGRESQL_PORT:-5432}:5432"
      KEYCLOAK_IMPORT: ./enterprise-solution-realm.json
      #KEYCLOAK_FRONTEND_URL: http://localhost:${KEYCLOAK_PORT:-8080}/auth/
    volumes:
      - keycloak:/tmp/keycloak
    ports:
      - "${KEYCLOAK_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - solution-network
     
  postgres:
    container_name: solution_postgres
    image: postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB:-keycloak}
      POSTGRES_USER: ${POSTGRESQL_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      #- ./sql-scripts.sql:/docker-entrypoint-initdb.d/sql-scripts.sql
    ports:
      - "${POSTGRESQL_PORT:-5432}:5432"
    networks:
      - solution-network
    restart: unless-stopped
  
  pgadmin:
    container_name: solution_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.host}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - solution-network
    restart: unless-stopped
    
  redisCache:
    container_name: solution_redisCache
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - solution-network
    volumes:
      - redis:/data

networks:
  solution-network:
    driver: bridge

volumes:
    keycloak:
    postgres:
    pgadmin:
    redis: